### ISSUE TITLE
Set up WartRemover for Scala 3

### ISSUE THREAD

**Issue by Kevin-Lee** [Kevin-Lee/just-semver#138]
# Task
## Summary
Set up [WartRemover](https://www.wartremover.org) for Scala 3.

## Project Details
Version: `0.4.0`

## Description
Now WartRemover support Scala 3 (3.1.1 and higher to be more precise) so set it up to use it.
- [ ] Set up `WartRemover` `3.0.0` which supports Scala `3`
- [ ] Don't set up `WartRemover` for Scala `3.0.x` since there's no `WartRemover` supporting `3.0.x`
- [ ] Set `WartRemover` `2.4.19` for Scala `2.11` since `WartRemover` `3.0.0` doesn't support Scala `2.11`.
